# Generated by Django 4.0.1 on 2022-01-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luz', models.CharField(default='0', max_length=20)),
                ('df', models.FloatField()),
                ('ram', models.IntegerField()),
                ('wifi_ip', models.CharField(default='0', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('Luz', models.IntegerField(primary_key=True, serialize=False)),
                ('encendido', models.BooleanField(default=False)),
                ('Ip', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('descripcion', models.CharField(default='A determinar', max_length=100)),
            ],
        ),
    ]
