# Generated by Django 4.0.1 on 2022-01-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='df',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='logger',
            name='ram',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
